#!/usr/bin/env python3
"""Generate a deterministic, binary-safe C++ table of embedded Lua scripts."""

from __future__ import annotations

import argparse
from pathlib import Path


def c_string(value: str) -> str:
    out = ['"']
    for byte in value.encode("utf-8"):
        if byte == 0x22:
            out.append('\\"')
        elif byte == 0x5C:
            out.append('\\\\')
        elif 0x20 <= byte < 0x7F:
            out.append(chr(byte))
        else:
            out.append(f"\\x{byte:02x}")
    out.append('"')
    return "".join(out)


def byte_rows(data: bytes) -> str:
    if not data:
        return "  0"
    rows = []
    for offset in range(0, len(data), 12):
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in data[offset : offset + 12]))
    return ",\n".join(rows)


def generate(sources: list[tuple[Path, str]], output_root: Path) -> int:
    entries: list[tuple[str, bytes]] = []
    seen: dict[str, Path] = {}
    for input_root, prefix in sources:
        files = sorted(path for path in input_root.rglob("*.lua") if path.is_file())
        for path in files:
            relative_path = path.relative_to(input_root).as_posix()
            clean_prefix = prefix.strip("/")
            logical_path = (
                f"{clean_prefix}/{relative_path}" if clean_prefix else relative_path
            )
            if logical_path in seen:
                raise ValueError(
                    f"logical path collision: {logical_path}: {seen[logical_path]} and {path}"
                )
            seen[logical_path] = path
            entries.append((logical_path, path.read_bytes()))
    entries.sort(key=lambda entry: entry[0])

    output_root.mkdir(parents=True, exist_ok=True)
    header = output_root / "embedded_lua.hpp"
    source = output_root / "embedded_lua.cpp"

    header.write_text(
        "// Generated by tools/generate_embedded_lua.py; do not edit.\n"
        "#pragma once\n\n"
        "#include <cstddef>\n"
        "#include <cstdint>\n\n"
        "namespace isaac_port::embedded_lua {\n\n"
        "struct LuaFile {\n"
        "    const char* path;\n"
        "    const std::uint8_t* bytes;\n"
        "    std::size_t size;\n"
        "};\n\n"
        "extern const LuaFile kFiles[];\n"
        "extern const std::size_t kFileCount;\n\n"
        "} // namespace isaac_port::embedded_lua\n",
        encoding="utf-8",
    )

    body = [
        "// Generated by tools/generate_embedded_lua.py; do not edit.",
        '#include "generated/embedded_lua.hpp"',
        "",
        "namespace isaac_port::embedded_lua {",
        "",
    ]
    for index, (_, data) in enumerate(entries):
        body.extend(
            [
                f"static const std::uint8_t kBytes{index}[] = {{",
                byte_rows(data),
                "};",
                "",
            ]
        )
    body.append("const LuaFile kFiles[] = {")
    for index, (path, data) in enumerate(entries):
        body.append(f"    {{{c_string(path)}, kBytes{index}, {len(data)}}},")
    body.extend(
        [
            "};",
            "",
            f"const std::size_t kFileCount = {len(entries)};",
            "",
            "} // namespace isaac_port::embedded_lua",
            "",
        ]
    )
    source.write_text("\n".join(body), encoding="utf-8", newline="\n")
    return len(entries)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--source",
        nargs=2,
        action="append",
        metavar=("ROOT", "PREFIX"),
        help="embed *.lua below ROOT under logical PREFIX (repeatable)",
    )
    # Keep the original one-root interface for callers outside the build.
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    sources = [(Path(root), prefix) for root, prefix in (args.source or [])]
    if args.input is not None:
        sources.append((args.input, ""))
    if not sources:
        parser.error("at least one --source ROOT PREFIX or --input ROOT is required")
    try:
        count = generate(sources, args.output)
    except ValueError as error:
        parser.error(str(error))
    print(f"Generated {count} Lua files in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
