#!/usr/bin/env python3
"""Generate explicit entity IDs from Repentance Plus XML."""

from __future__ import annotations

import argparse
from pathlib import Path
import xml.etree.ElementTree as ET


def quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mod", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    root = ET.parse(args.mod / "content/entities2.xml").getroot()
    entries = []
    for entity in root.findall("entity"):
        name = entity.get("name")
        type_id = entity.get("id")
        if not name or type_id is None:
            continue
        entries.append((name, int(type_id, 0), int(entity.get("variant", "0"), 0)))
    entries.sort()

    args.output.mkdir(parents=True, exist_ok=True)
    target = args.output / "mod_ids.hpp"
    rows = "\n".join(
        f"    {{{quote(name)}, {type_id}, {variant}}},"
        for name, type_id, variant in entries
    )
    target.write_text(
        "// Generated by tools/generate_mod_ids.py; do not edit.\n"
        "#pragma once\n\n"
        "#include <cstddef>\n\n"
        "namespace isaac_port::mod_ids {\n\n"
        "struct EntityId { const char* name; int type; int variant; };\n"
        "inline constexpr EntityId kEntities[] = {\n"
        f"{rows}\n"
        "};\n"
        "inline constexpr std::size_t kEntityCount = "
        "sizeof(kEntities) / sizeof(kEntities[0]);\n\n"
        "} // namespace isaac_port::mod_ids\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated {len(entries)} entity IDs in {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
